Trabalho_Conclusao/Trabalho_Conclusao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
<<<<<<< Updated upstream
    path('', include('login.urls')),
=======
    path('', include('users.urls')),
>>>>>>> Stashed changes
]

Trabalho_Conclusao/homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index")
]

Trabalho_Conclusao/login/urls.py
from django.urls import path
from . import views
<<<<<<< Updated upstream
# from django.views.generic import RedirectView

# # from users.views.user_management import UserListView, UserUpdateView, UserCreateView, UserDeleteView, UserSearchView
# # from users.views.auth import UserLoginView, UserLogoutView
# from django.contrib.auth.views import PasswordChangeView

app_name = "users"
urlpatterns = [
#     path("login/", UserLoginView.as_view(), name="login"),
#     path("logout/", UserLogoutView.as_view(), name="logout"),
#     path("usuarios/", UserListView.as_view(), name="index"),
#     path("usuarios/cadastro/", UserCreateView.as_view(), name="create"),
#     path("users/<int:pk>/delete", UserDeleteView.as_view(), name="delete"),
#     path("users/search", UserSearchView.as_view(), name="search"),
#     path("usuarios/<int:pk>/", UserUpdateView.as_view(), name="update"),
#     path("", RedirectView.as_view(url="login/", permanent=True)),
    path("usuarios/", views.index, name="index"),
    path("usuarios/cadastro/", views.create, name="create"),
    path("login/", views.login, name="login"),
=======

app_name= "users"
urlpatterns = [
    path("cadastro/". views.create, name="create"),
    path("/login". views.login, name="login"),
>>>>>>> Stashed changes
]

Trabalho_Conclusao/roteiro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.roteiro, name="roteiro")
]

Trabalho_Conclusao/compra/models.py
from django.db import models

# Create your models here.

Trabalho_Conclusao/homepage/models.py
from django.db import models

# Create your models here.

Trabalho_Conclusao/login/models.py
from django.db import models
<<<<<<< Updated upstream
=======

# Create your models here.

class User(models.Model):
    company_name = models.CharField(max_length=255)
    fantasy_name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True)
    representative = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=20)
    email = models.EmailField()
    zipcode = models.CharField(max_length=20)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=20)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    phone = models.CharField(max_length=20)
    enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
>>>>>>> Stashed changes

Trabalho_Conclusao/perfil/models.py
from django.db import models

# Create your models here.

Trabalho_Conclusao/registro/models.py
from django.db import models

# Create your models here.

Trabalho_Conclusao/roteiro/models.py
from django.db import models

# Create your models here.

Trabalho_Conclusao/login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

class UserForm(forms.ModelForm):
<<<<<<< Updated upstream
=======
    
>>>>>>> Stashed changes
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "password"]
        widgets = {
            "password": forms.PasswordInput()
        }
        
<<<<<<< Updated upstream
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["username"].help_text = "Informe um endereço de e-mail válido como usuário."
        
    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        
        password = cleaned_data.get("password")
        
        # Criptografando a senha
        if password:
            user.set_password(password)
        
        if commit:
            user.save()
        
        return user
        
=======
        __init__(self, *args, **kwargs)
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        
    def save(self, commit=True):
        password = self.cleaned_data.get("password")
        
        user = super().save(commit=False)   
        
        #Hash da senha     
        if password:
            user.set_password(password)
            
        if commit:
            user.save()
            
        return user
    
>>>>>>> Stashed changes
    def clean(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        
        if first_name == last_name:
<<<<<<< Updated upstream
            self.add_error("first_name", ValidationError("O primeiro nome não pode ser igual ao último nome."))
            self.add_error("last_name", ValidationError("O primeiro nome não pode ser igual ao último nome."))
        
        # Validar se o username é um e-mail válido
=======
            self.add_error("first_name", ValidationError("O primeiro nome não pode ser igual ao último nome"))
            self.add_error("last_name", ValidationError("O primeiro nome não pode ser igual ao último nome"))
        
>>>>>>> Stashed changes
        username = self.cleaned_data.get("username")
        
        try:
            validate_email(username)
        except ValidationError:
<<<<<<< Updated upstream
            self.add_error("username", ValidationError("Informe um endereço de e-mail válido para o nome de usuário."))

        
        return super().clean()
    
=======
            self.add_error("username", ValidationError("Informe um endereço de e-mail válido"))
                           
        return super().clean()
            
>>>>>>> Stashed changes

Trabalho_Conclusao/compra/views.py
from django.shortcuts import render

# Create your views here.

Trabalho_Conclusao/homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "index.html")

Trabalho_Conclusao/login/views.py
<<<<<<< Updated upstream
from django.contrib import messages, auth
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.urls import reverse
from .forms import UserForm
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.

def index(request):
    users = User.objects.all().order_by("-id")
    
    context = {
        "users": users
    }
    
    return render(request, "users/index.html", context)

def create(request):
    
    form_action = reverse("users:create")
    
    #POST
    if request.method == "POST":
        form = UserForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, "O usuário foi cadastrado com sucesso!")
            
            return redirect("users:index")
        
        context = {
            "form": form
        }
        
        return render(request, "users/create.html", context)
    
    # GET
    
    form = UserForm()
    
    context = {
        "form": form
    }
    
    return render(request, "users/create.html", context)

def login(request):
    #POST
    
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)

            return redirect("homepage:index")
        
    #GET
    form = AuthenticationForm(request)
    
    context = {
        "form": form
    }
    
    return render(request, "users/login.html", context)
=======
from django.shortcuts import render
from django.contrib.auth.models import User

def create(request):
    return render(request, "users/create.html")

def login(request):
    return render(request, "users/login.html")
>>>>>>> Stashed changes

Trabalho_Conclusao/perfil/views.py
from django.shortcuts import render

# Create your views here.

Trabalho_Conclusao/registro/views.py
from django.shortcuts import render

# Create your views here.

Trabalho_Conclusao/roteiro/views.py
# Create your views here.
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "roteiro.html")

Trabalho_Conclusao/base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Travel Connect - {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}" />
    <!-- Icons do bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <!-- Icons do google fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'base/js/base.js' %}"></script>
    {% block head %}{% endblock %}
</head>

<body>
    <header>
        <div style="display: flex; justify-content: space-around; padding-top: 1.5em;" >
            <div style="margin: 0;">
                <p style="margin: 0; font-weight: bold; color: white;">Travel</p>
                <p style="margin: 0; font-weight: bold; color: white;">Connect</p>
            </div>
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style="border-radius: 50px; width: 50em; margin: 0.7em;">
            </form>
            <i class="bi bi-filter-circle-fill"></i>
        </div>
    </header>

    <nav>
        <div class="custom-container">
            <div class="d-flex menu-display">
                <!-- Menu -->
                <div class="menu border d-flex flex-column align-items-center justify-content-center" ><i class="bi bi-book menu-icons"></i><p>Cultural</p></div>
                <div class="menu border d-flex flex-column align-items-center justify-content-center"><i class="bi bi-map menu-icons"></i><p>Aventura</p></div>
                <!-- Os icons abaixo são do google fonts, pois não foram localizados icons parecidos no bootstrap -->
                <div class="menu border d-flex flex-column align-items-center justify-content-center"> <span class="material-symbols-outlined">nightlife</span><p>Agitada</p></div>
                <div class="menu border d-flex flex-column align-items-center justify-content-center"><span class="material-symbols-outlined">history_edu</span><p>Histórica</p></div>
                <div class="menu border d-flex flex-column align-items-center justify-content-center"><span class="material-symbols-outlined">surfing</span><p>Verão</p></div> 
                <div class="menu border d-flex flex-column align-items-center justify-content-center"><span class="material-symbols-outlined">ac_unit</span><p>Inverno</p></div>
            </div>
        </div>
    </nav>
    <main>
        <div class="container">
            {% block content %}{% endblock  %}
        </div>
    </main>
    
    <footer>
        <div class="d-flex justify-content-between ">
            <div class="d-flex flex-column footer_contact">
                <div><i class="bi bi-geo-alt-fill"></i> <span>Bela Vista, Palhoça</span></div>
                <div><i class="bi bi-telephone-fill"></i> <span>(47) 99999-9999</span></div>
                <div><i class="bi bi-envelope-fill"></i> <span>travelconnect@contato.com</span></div>
                <p>&copy; <span>Travel Connect</span>, All Right Reserved.</p>
            </div>

            <div class="footer_suport">
                <p>Trabalhe conosco</p>
                <p>Contato</p>
                <p>Política de privacidade</p>
                <p>Termos e condições</p>
                <p>Suporte</p>
            </div>
        </div>
    </footer>
</body>

</html>

Trabalho_Conclusao/homepage/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Homepage{% endblock  %}
{% block head %}

{% endblock  %}

{% block content %}

    <div class="div-margin d-flex justify-content-between">
        <h2 style="display: inline;">Destinos recomendados</h2>
        <span style="display: inline-block; margin-left: 10px;">Ver mais<i class="bi bi-arrow-right"></i></span>
    </div>
    <div>
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-5 ">
            <div class="col">
                <div class="card h-100" style="border-radius: 20px; background-color:  #F8F8F8;"> <!--Somente foi possível modificar o border-radius diretamente na tag-->
                    <img src= "{% static 'base/img/paris.jpg' %}" class="card-img-top custom-img" style="border-radius: 20px; " alt="..."> <!--Somente foi possível modificar o border-radius diretamente na tag-->
                    <div class="card-body custom-border" style="height: 11em;">
                        <h5 class="card-title d-flex justify-content-between " style="color: #122A3E;">Paris <i class="bi bi-heart favorite-icon-recommended"></i></h5>
                        <p class="card-text mb-0">Duração:</p>
                        <p class="card-text">7 dias e 6 noites</p>
                        <p class="card-text">A partir de: R$000,00</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100" style="border-radius: 20px; background-color:  #F8F8F8;"> <!--Somente foi possível modificar o border-radius diretamente na tag-->
                    <img src= "{% static 'base/img/veneza.jpg' %}" class="card-img-top custom-img" style="border-radius: 20px;" alt="..."> <!--Somente foi possível modificar o border-radius diretamente na tag-->
                    <div class="card-body custom-border">
                        <h5 class="card-title d-flex justify-content-between" style="color: #122A3E;">Veneza<i class="bi bi-heart favorite-icon-recommended"></i></h5>
                        <p class="card-text mb-0">Duração:</p>
                        <p class="card-text">10 dias e 9 noites</p>
                        <p class="card-text">A partir de: R$000,00</p>                        </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100" style="border-radius: 20px; background-color:  #F8F8F8;"> <!--Somente foi possível modificar o border-radius diretamente na tag-->
                    <img src= "{% static 'base/img/peru.jpg' %}" class="card-img-top custom-img" style="border-radius: 20px" alt="..."> <!--Somente foi possível modificar o border-radius diretamente na tag-->
                    <div class="card-body custom-border">
                        <h5 class="card-title d-flex justify-content-between " style="color: #122A3E;">Machu Pichu<i class="bi bi-heart favorite-icon-recommended"></i></h5>
                        <p class="card-text mb-0">Duração:</p>
                        <p class="card-text">5 dias e 4 noites</p>
                        <p class="card-text">A partir de: R$000,00</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Explorar pacotes -->
    <div class="div-margin d-flex justify-content-between">
        <h2 style="display: inline;">Explorar nossos pacotes</h2>
        <span style="display: inline-block; margin-left: 10px;">Ver mais<i class="bi bi-arrow-right"></i></span>
    </div>
    <div class="card mb-4" style="border-radius: 20px;">
        <div class="row g-0 custom-background custom-border">
            <div class="col-md-6">
                <img src= "{% static 'base/img/recife.jpg' %}" class="img-fluid  img-fluid-custom" style=" height: 20em" alt="..."><!--A altura da imagem só foi possível alterar diretamente pela tag-->
            </div>
            <div class="col-md-6">
                <div class="card-body ">
                    <h3 class="card-title d-flex justify-content-between" style="color: #122A3E;">Recife<i class="bi bi-heart favorite-icon-package"></i></h3>
                    <div>Histórica</div>
                    <p class="card-text">5 dias e 4 noites</p>
                    <p>A partir de: R$000,00</p>
                </div>
            </div>
        </div>
    </div>
    <div class="card mb-4" style="border-radius: 20px;">
        <div class="row g-0 custom-background custom-border">
            <div class="col-md-6">
                <img src="{% static 'base/img/santorini.jpg' %}" class="img-fluid img-fluid-custom" style="height: 20em;" alt="..."> <!--A altura da imagem só foi possível alterar diretamente pela tag-->
            </div>
            <div class="col-md-6">
                <div class="card-body ">
                    <h3 class="card-title d-flex justify-content-between" style="color: #122A3E;">Santorini<i class="bi bi-heart favorite-icon-package"></i></h3>
                    <div>Romântica</div>
                    <p class="card-text">5 dias e 4 noites</p>
                    <p>A partir de: R$000,00</p>
                </div>
            </div>
        </div>
    </div>
    <div class="card mb-5" style="border-radius: 20px;">
        <div class="row g-0 custom-background custom-border">
            <div class="col-md-6">
                <img src="{% static 'base/img/veneza.jpg' %}" class="img-fluid img-fluid-custom" style="height: 20em;" alt="..."><!--A altura da imagem só foi possível alterar diretamente pela tag-->
            </div>
            <div class="col-md-6">
                <div class="card-body ">
                    <h3 class="card-title d-flex justify-content-between" style="color: #122A3E;">Bariloche<i class="bi bi-heart favorite-icon-package"></i></h3>
                    <div>Inverno</div>
                    <p class="card-text">5 dias e 4 noites</p>
                    <p>A partir de: R$000,00</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

Trabalho_Conclusao/login/templates/users/create.html
<<<<<<< Updated upstream
{% extends "base.html" %} 
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  Cadastro de Usuário
{% endblock %}
{% block content %} 

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card-md-6">
                <h2 class="mt-5">Cadastro de Usuários</h2>
                <form action="{{ form_action }}" method="post">
                    {% csrf_token %}

                    {{ form|crispy }}
                
                    <div class="d-grid mb-5">
                        <button class="btn btn-primary btn-lg">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
=======
{% extends "base.html" %}
{% load static %}
{% block title %}
Login
{% endblock  %}
{% block head %}
    <script src="{% static 'base/js/index.js' %}"></script>
{% endblock %}
{% block content %}
<h2>usuários</h2>



>>>>>>> Stashed changes
{% endblock %}

Trabalho_Conclusao/login/templates/users/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Usuários
{% endblock %}
{% block head %}

{% endblock %}
{% block content %}

    <h2 class="mb-3">Usuários</h2>

<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Username</th>
                <th>Ativo</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.first_name|title }} {{ user.last_name|title }}</td>
                <td>{{ user.username }}</td>
                <td>
                    <input {% if user.enable  %}checked{% endif %} type="checkbox" class="form-check-input">
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

Trabalho_Conclusao/login/templates/users/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Travel Connect - Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'base/css/login.css' %}">
  </head>
  <body>
    <h1 class="title_pagina">TravelConnect</h1>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card-md-6">
              <p class="subtitle">Explore lugares incrível ao redor do mundo.</p>
            </div>
            <div class="card-body">
              <form action="{% url 'users:login' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Entrar</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <a href="{% url "users:create" %}" class="link" title="Não possui uma conta? Criar">
          <p>Não possui uma conta? <b>Criar</b></p>
        </a> 
      </div>

      <div class="container">
        <a href="{% url "homepage:index" %}" class="link" title="Não possui uma conta? Criar">
          <p>Continuar sem conta</p>
        </a> 
      </div>
      
  </body>
</html>

Trabalho_Conclusao/roteiro/templates/roteiro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Roteiro
{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'base/css/roteiro.css' %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
{% endblock %}

{% block content %}
  <body>
    <div class="container">
      <div class="imagens">
        <img src="{% static 'base/img/veneza1.png' %}" alt="" class="img1" />
        <img src="{% static 'base/img/veneza2.png' %}" alt="" class="img2" />
        <img src="{% static 'base/img/veneza3.png' %}" alt="" class="img3" />
      </div>
      <div class="roteiro">
        <div class="titulo">
          <h1>Veneza</h1>
          <p>Navegando pelos encantos de uma cidade dos sonhos</p>
        </div>
        <div class="sobre">
          <h2>Sobre a viagem</h2>
          <p>Lorem ipsum dolor sit amet consectetur. Sed bibendum tortor mi integer tellus nam nunc malesuada. Turpis et leo adipiscing semper. Quam consequat pretium eu duis mauris auctor tristique curabitur. Faucibus etiam amet tincidunt sit gravida pellentesque eu at. Aliquam accumsan nibh habitant feugiat. Nisi consequat vitae bibendum blandit aenean nunc. Sed purus sit fames cras massa. In orci in non tellus at donec non blandit proin. Viverra a eget et vulputate. Tristique risus varius massa ullamcorper pellentesque auctor pellentesque. Tellus odio commodo faucibus augue.In orci in non tellus at donec non blandit proin. Viverra a eget et vulputate. Tristique risus varius massa ullamcorper pellentesque auctor pellentesque. Tellus odio commodo faucibus augue.</p>
        </div>
        <div class="valor-duracao">
          <div class="valor">
            <h5><i class="bi bi-tag"></i>Valor</h5>
            <h4>R$ 0000,00</h4>
          </div>
          <div class="duracao">
            <h5><i class="bi bi-clock"></i>Duração</h5>
            <h4>10 dias e 9 noites</h4>
          </div>
          <button>Reservar sua viagem</button>
        </div>
      </div>
    </div>
    <div class="bloco-review">
      <div class="compartilhe">
        <h2>Compartilhe sua aventura</h2>
        <p>Histórias de viagens dos nossos exploradores</p>
      </div>
      <div class="reviews">
        <div class="bloco">
          <h2>"</h2>
          <p>Lorem ipsum dolor sit amet consectetur. Nibh sagittis imperdiet vitae ipsum sem. Morbi odio duis ipsum risus.</p>
          <div class="overlay">
            <img src="{% static 'base/img/perfil1.png' %}" alt="" class="foto-perfil" />
            <h4>Maria</h4>
            <h5>Turista</h5>
          </div>
        </div>
        <div class="bloco">
          <h2>"</h2>
          <p>Lorem ipsum dolor sit amet consectetur. Nibh sagittis imperdiet vitae ipsum sem. Morbi odio duis ipsum risus.</p>
          <div class="overlay">
            <img src="{% static 'base/img/perfil2.png' %}" alt="" class="foto-perfil" />
            <h4>Pedro</h4>
            <h5>Turista</h5>
          </div>
        </div>
        <div class="bloco">
          <h2>"</h2>
          <p>Lorem ipsum dolor sit amet consectetur. Nibh sagittis imperdiet vitae ipsum sem. Morbi odio duis ipsum risus.</p>
          <div class="overlay">
            <img src="{% static 'base/img/perfil3.png' %}" alt="" class="foto-perfil" />
            <h4>Ana Júlia</h4>
            <h5>Turista</h5>
          </div>
        </div>
        <div class="bloco">
          <h2>"</h2>
          <p>Lorem ipsum dolor sit amet consectetur. Nibh sagittis imperdiet vitae ipsum sem. Morbi odio duis ipsum risus.</p>
          <div class="overlay">
            <img src="{% static 'base/img/perfil4.png' %}" alt="" class="foto-perfil" />
            <h4>Gabriel</h4>
            <h5>Turista</h5>
          </div>
        </div>
      </div>
    </div>
  </body>
{% endblock %}